### ISSUE TITLE
undefined method `dynamic_selectable

### ISSUE THREAD

**Issue by dcalixto** [ATNI/dynamic_selectable#10]
Hi  @mattantonelli, i followed your steps and configured the dynamic_selectable but rails spitting out:

 undefined method `dynamic_selectable_[#<Gender id: 1, slug: "masculino", gender: "Masculino", created_at: "2015-12-29 20:26:14", updated_at: "2015-12-29 20:26:14">, #<Gender id: 2, slug: "feminino", gender: "Feminino", created_at: "2015-12-29 20:26:23", updated_at: "2015-12-29 20:26:23">, #<Gender id: 3, slug: "infantil", gender: "Infantil", created_at: "2015-12-29 20:26:31", updated_at: "2015-12-29 20:26:31">]_ids_path' for #<#<Class:0x007f8904086328>:0x007f890991a728>

**Comment by dcalixto** [comment]
by the way, congratulations, great gem.

**Comment by mattantonelli** [comment]
Hi @dcalixto. Have you updated to 1.0.0 or are you still running 0.0.2? There were some major changes in this upgrade, and at the very least you will need to re-run your `rails generate dynamic_selectable:select`. If you'd like to continue using code from 0.0.2 you can reference that specific branch in your Gemfile.

If you can reproduce the issue in a repo I can clone, I'd be happy to take a look at it. You may also want to check out the [sample project](https://github.com/mattantonelli/dynamic-selectable-test) for examples of the 1.0.0 version of the gem.

**Comment by dcalixto** [comment]
Hello, @mattantonelli, i'm using 1.0.0. but i fork it and downgrade the rails 3.2 that i'm using. so, have any problem with rails 3?

**Comment by mattantonelli** [comment]
The projects this gem was designed for are all on Rails 4, so I haven't done any testing for Rails 3. Would you be able to reproduce this issue in a new Rails 3.2 project for me to take a look at?

**Comment by mattantonelli** [comment]
Closing this for now. Feel free to reopen if you can reproduce this in something I can take a look at.
