### ISSUE TITLE
Support for Rails 5

### ISSUE THREAD

**Issue by Atrain2020** [ATNI/dynamic_selectable#12]
Looks like a useful gem.... can we please have support for Rails 5? Unsurprisingly, attempting an install as per the README instructions on a Rails 5 project raises dependency errors.

**Comment by mattantonelli** [comment]
Thanks for your interest! I'm still hanging out in 4.1 and have yet to dive into Rails 5. But when I do, I will certainly consider updating this gem.

**Comment by mattantonelli** [comment]
@Atrain2020 It doesn't look like Rails 5 introduced any breaking changes, so I went ahead and loosened the Rails dependency to work with Rails 5. (#13) I have also updated the [sample app](https://github.com/mattantonelli/dynamic-selectable-test) and everything seems to be in working order.

If you decide to use the gem and run into any trouble, feel free to send another issue my way!
