### ISSUE TITLE
Turbolinks 5 support

### ISSUE THREAD

**Issue by mattantonelli** [ATNI/dynamic_selectable#15]
With Turbolinks 5, scripts fired on the initial page load will no longer be re-run when the page is revisited. The coffeescript should be updated to either look for the `turbolinks:load` event or the listener should be updated to use event delegation.

A more detailed explanation of the issue can be found [here](https://github.com/turbolinks/turbolinks#running-javascript-when-a-page-loads).

**Comment by schie** [comment]
```Coffeescript
ds = -> $('select[data-dynamic-selectable-url][data-dynamic-selectable-target]').dynamicSelectable()

if $.turbo
	$(document).on 'turbolinks:load', ds
else
	$ ds
```

**Comment by schie** [comment]
Here are some things I've noticed:

|              |`$.turbo`|`Turbolinks`|
|---------:|:--------:|-----------:|
|nothing | No       |         No| 
|< 5        | Yes      |         Yes| 
|5           | No       |         Yes|

Here's one option, but I don't like it:
```CoffeeScript

createDynamicSelectable = -> $('select[data-dynamic-selectable-url][data-dynamic-selectable-target]').dynamicSelectable()


$ ->
  try
    tl = Turbolinks
  if $.turbo
    $(createDynamicSelectable)
  else
    $(document).on 'turbolinks:load', createDynamicSelectable
  catch (e)
    if e instanceof ReferenceError
      $(createDynamicSelectable)
    else
      console.log('something went wrong with creating dynamic selectalbe #{e}')
  finally
    console.log('something went wrong with creating dynamic selectable')

```

**Comment by mattantonelli** [comment]
Closing this since it is really more of an issue with Turbolinks itself. Anyone having issues using this gem with Turbolinks 5 should consider using an older version of Turbolinks or using the [compatibility shim](https://github.com/turbolinks/turbolinks/blob/master/src/turbolinks/compatibility.coffee) provided by that library.

An updated version of [jquery.turbolinks](https://github.com/kossnocorp/jquery.turbolinks) also has the potential to resolve this issue.
